# Generated by Django 4.2.2 on 2024-07-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=42),
        ),
    ]
